version: 0.0
os: linux
files:
  - source: app
    destination: /home/ec2-user/flask-app/app
  - source: cicd/scripts
    destination: /home/ec2-user/flask-app/scripts
hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 60
      runas: ec2-user
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ec2-user
